//#region "Security"
//// USERS MODULE
export const CREATE_USER_PERMISSION_ID = 1;
export const MODIFY_ACCESS_PASSWORD_ID = 2;
export const DISABLE_USER_PERMISSION_ID = 3;
export const UPDATE_USER_PROFILE_ID = 89;

//// ROLES MODULE
export const CREATE_ROLE_PERMISSION_ID = 4;
export const ASSIGN_ROLE_PERMISSION_ID = 5;
export const UPDATE_ROLE_PERMISSION_ID = 90;

//// GENERAL MASTERS MODULE
export const MANAGE_MASTER_PERMISSION_ID = 7;
export const CREATE_ROLE_MASTER_PERMISSION_ID = 11;

//// TASKS MODULE
export const MANAGE_TASK_PERMISSION_ID = 6;

//// MILESTONES MODULE
export const MANAGE_MILESTONES_PERMISSION_ID = 10;

//#endregion

//#region "General Masters"

//// COUNTRIES MODULE
export const CHECK_COUNTRY_PERMISSION_ID = 8;
export const UPDATE_COUNTRY_PERMISSION_ID = 9;
export const INACTIVATE_STATUS_COUNTRY_PERMISSION_ID = 129;

//// PROVINCE MODULE
export const CHECK_STATE_PERMISSION_ID = 12;
export const UPDATE_STATE_PERMISSION_ID = 13;

//// COMPANIES MODULE
export const CHECK_COMPANIES_PERMISSION_ID = 14;
export const UPDATE_COMPANIES_PERMISSION_ID = 34;
export const INACTIVATE_STATUS_COMPANIES_PERMISSION_ID = 130;

//// CITIES MODULE
export const CHECK_CITIES_PERMISSION_ID = 15;
export const UPDATE_CITIES_PERMISSION_ID = 35;

//// CURRENCY MODULE
export const CHECK_CURRENCY_PERMISSION_ID = 16;
export const UPDATE_CURRENCY_PERMISSION_ID = 36;

//// DISTRICT MODULE
export const CHECK_DISTRICT_PERMISSION_ID = 17;
export const UPDATE_DISTRICT_PERMISSION_ID = 37;

//// BRAND MODULE
export const CHECK_BRAND_PERMISSION_ID = 19;
export const UPDATE_BRAND_PERMISSION_ID = 39;

//// PORT MODULE
export const CHECK_PORT_PERMISSION_ID = 18;
export const UPDATE_PORT_PERMISSION_ID = 38;

//// DIVICE TYPES MODULE
export const CHECK_DIVICE_TYPES_PERMISSION_ID = 20;
export const UPDATE_DIVICE_TYPES_PERMISSION_ID = 40;

//// DIVICES MODULE
export const CHECK_DIVICES_PERMISSION_ID = 21;
export const UPDATE_DIVICES_PERMISSION_ID = 41;

//// BANKS MODULE
export const CHECK_BANKS_PERMISSION_ID = 22;
export const UPDATE_BANKS_PERMISSION_ID = 42;

//// SUBSIDIARIES MODULE
export const CHECK_SUBSIDIARIES_PERMISSION_ID = 23;
export const UPDATE_SUBSIDIARIES_PERMISSION_ID = 43;

//// AREAS MODULE
export const CHECK_AREAS_PERMISSION_ID = 24;
export const UPDATE_AREAS_PERMISSION_ID = 44;

//// TAXES MODULE
export const CHECK_TAXES_PERMISSION_ID = 25;
export const UPDATE_TAXES_PERMISSION_ID = 45;

//// TAX RATES MODULE
export const CHECK_TAX_RATES_PERMISSION_ID = 26;
export const UPDATE_TAX_RATES_PERMISSION_ID = 46;

//// MOTIVES TYPES MODULE
export const CHECK_MOTIVES_TYPES_PERMISSION_ID = 27;
export const UPDATE_MOTIVES_TYPES_PERMISSION_ID = 47;

//// MOTIVES MODULE
export const CHECK_MOTIVES_PERMISSION_ID = 28;
export const UPDATE_MOTIVES_PERMISSION_ID = 48;

//// PRICE GROUPING MODULE
export const CHECK_PRICE_GROUPING_PERMISSION_ID = 29;
export const UPDATE_PRICE_GROUPING_PERMISSION_ID = 49;

//// PRICE TYPES MODULE
export const CHECK_PRICE_TYPES_PERMISSION_ID = 30;
export const UPDATE_PRICE_TYPES_PERMISSION_ID = 50;

//// TAXE TYPE APPLICATION MODULE
export const CHECK_TAXE_TYPE_APPLICATION_PERMISSION_ID = 31;
export const UPDATE_TAXE_TYPE_APPLICATION_PERMISSION_ID = 51;

//// PAYMENT METHODS MODULE
export const CHECK_PAYMENT_METHODS_PERMISSION_ID = 32;
export const UPDATE_PAYMENT_METHODS_PERMISSION_ID = 52;

//// DOCUMENT TYPES MODULE
export const CHECK_DOCUMENT_TYPES_PERMISSION_ID = 33;
export const UPDATE_DOCUMENT_TYPES_PERMISSION_ID = 53;

//// BRANCH OFFICE MODULE
export const CHECK_BRANCH_OFFICES_PERMISSION_ID = 23;
export const UPDATE_BRANCH_OFFICES_PERMISSION_ID = 43;
export const INACTIVATE_STATUS_BRANCH_OFFICES_PERMISSION_ID = 131;

//// DIVICES MODULE
export const CHECK_SUPPLIERS_PERMISSION_ID = 242;
export const UPDATE_SUPPLIERS_PERMISSION_ID = 243;


//// EXCHANGE RATE MODULE
export const CHECK_EXCHANGE_RATE_PERMISSION_ID = 479;
export const UPDATE_EXCHANGE_RATE_PERMISSION_ID = 480;

//#endregion

//#region "MPC"
export const MANAGE_MPC_PERMISSION_ID = 54;

//// MEASURE GROUPING MODULE
export const CHECK_MEASURE_GROUPING_PERMISSION_ID = 55;
export const UPDATE_MEASURE_GROUPING_PERMISSION_ID = 56;

//// MEASUREMENT UNITS MODULE
export const CHECK_MEASUREMENT_UNITS_PERMISSION_ID = 57;
export const UPDATE_MEASUREMENT_UNITS_PERMISSION_ID = 58;

//// ATTRIBUTES GROUPING MODULE
export const CHECK_ATTRIBUTES_GROUPING_PERMISSION_ID = 59;
export const UPDATE_ATTRIBUTES_GROUPING_PERMISSION_ID = 60;

//// ATTRIBUTES MODULE
export const CHECK_ATTRIBUTES_PERMISSION_ID = 61;
export const UPDATE_ATTRIBUTES_PERMISSION_ID = 62;

//// ATTRIBUTE OPTIONS MODULE
export const CHECK_ATTRIBUTE_OPTIONS_PERMISSION_ID = 63;
export const UPDATE_ATTRIBUTE_OPTIONS_PERMISSION_ID = 64;

//// PACKAGING PRESENTATION MODULE
export const CHECK_PACKAGING_PRESENTATION_PERMISSION_ID = 65;
export const UPDATE_PACKAGING_PRESENTATION_PERMISSION_ID = 94;

//// PACKAGING USES MODULE
export const CHECK_PACKAGING_USES_PERMISSION_ID = 66;
export const UPDATE_PACKAGING_USES_PERMISSION_ID = 95;

//// GTIN TYPE MODULE
export const CHECK_GTIN_TYPE_PERMISSION_ID = 67;
export const UPDATE_GTIN_TYPE_PERMISSION_ID = 68;

//// MULTIMEDIA USES MODULE
export const CHECK_MULTIMEDIA_USES_PERMISSION_ID = 69;
export const UPDATE_MULTIMEDIA_USES_PERMISSION_ID = 70;

//// PRODUCT ASSOCIATIONS MODULE
export const CHECK_PRODUCT_ASSOCIATIONS_PERMISSION_ID = 71;
export const UPDATE_PRODUCT_ASSOCIATIONS_PERMISSION_ID = 72;

//// CLASSIFICATIONS MODULE
export const CHECK_CLASSIFICATIONS_PERMISSION_ID = 73;
export const UPDATE_CLASSIFICATIONS_PERMISSION_ID = 74;

//// PRODUCT CATEGORIES MODULE
export const CHECK_PRODUCT_CATEGORIES_PERMISSION_ID = 75;
export const UPDATE_PRODUCT_CATEGORIES_PERMISSION_ID = 76;
export const CHANGE_LEVEL_CATEGORIES_PERMISSION_ID = 116;

//// VALIDATION RANGES MODULE
export const CHECK_VALIDATION_RANGES_PERMISSION_ID = 77;
export const UPDATE_VALIDATION_RANGES_PERMISSION_ID = 78;

////  SOURCE TYPES MODULE
export const CHECK_SOURCE_TYPES_PERMISSION_ID = 79;
export const UPDATE_SOURCE_TYPES_PERMISSION_ID = 80;

//// DESCRIPTION TYPES MODULE
export const CHECK_DESCRIPTION_TYPES_PERMISSION_ID = 81;
export const UPDATE_DESCRIPTION_TYPES_PERMISSION_ID = 82;

//// DECREASE TYPES MODULE
export const CHECK_DECREASE_TYPES_PERMISSION_ID = 83;
export const UPDATE_DECREASE_TYPES_PERMISSION_ID = 84;

//// TYPE OF PRODUCTS TYPES MODULES
export const CHECK_TYPE_PRODUCT_PARTS_PERMISSION_ID = 85;
export const UPDATE_TYPE_PRODUCT_PARTS_PERMISSION_ID = 86;

//// NORMATIVES
export const CHECK_NORMATIVE_PERMISSION_ID = 240;
export const UPDATE_NORMATIVE_PERMISSION_ID = 241;


//// INSERT TYPE MODULES
export const CHECK_INSERT_TYPE_PERMISSION_ID = 96;
export const UPDATE_INSERT_TYPE_PERMISSION_ID = 97;

//// PRODUCT CATALOG
export const CHECK_PRODUCT_CATALOG_PERMISSION_ID = 107;
export const CHECK_PRODUCT_PERMISSION_ID = 109;
export const MANAGE_GENERAL_SECTION_PERMISSION_ID = 110;
export const MANAGE_COMPLEMENTARY_SECTION_PERMISSION_ID = 111;
export const MANAGE_PUBLICATIONS_SECTION_PERMISSION_ID = 112;
export const MANAGE_QUALITY_CONTROL_SECTION_PERMISSION_ID = 113;
export const MANAGE_SPECIFICATION_PRODUCT_SECTION_PERMISSION_ID=233;
export const DELETE_SPECIFICATION_PRODUCT_SECTION_PERMISSION_ID=235;

export const UPDATE_FINISH_PRODUCT_PERMISSION_ID = 114;
export const UPDATE_CANCEL_PRODUCT_PERMISSION_ID = 115;
export const UPDATE_PRODUCT_PERMISSION_ID = 108;
export const MANAGE_ASSOCIATION_SECTION_PERMISSION_ID = 156;
export const CHECK_BRANCH_OFFICE_SECTION_PERMISSION_ID = 157;
export const MANAGE_LOGISTIC_DATA_SECTION_PERMISSION_ID = 158;
export const INACTIVATE_BRANCH_PRODUCT_PERMISSION_ID = 159;
export const MANAGE_PRICES_COSTS_PERMISSION_ID = 160;
export const MANAGE_VALIDATION_FACTOR_PERMISSION_ID = 161;
export const MANAGE_POINT_ORDER_PERMISSION_ID = 162;
export const MANAGE_INDICATORS_BRANCH_PRODUCT_PERMISSION_ID = 163;
export const EDIT_PRICES_PERMISSION_ID = 216;
export const EDIT_COSTS_PERMISSION_ID = 217;
export const CHECK_PRICES_PERMISSION_ID = 218;
export const CHECK_COSTS_PERMISSION_ID = 219;
export const MANAGE_TAXES_DATA_SECTION_PERMISSION_ID = 234;

//VIEWER PRODUCT BRANCH
export const MANAGE_INDICATORS_LOGISTIC_DATA_SECTION_PERMISSION_ID = 256;

//#endregion "Mpc Masters"

//#region "IMS"
export const CHECK_GROUPING_INVENTORY_REASON_PERMISSION_ID = 103;
export const UPDATE_INSERT_GROUPING_INVENTORY_REASON_PERMISSION_ID = 104;

export const CHECK_INVENTORY_REASON_PERMISSION_ID = 105;
export const UPDATE_INVENTORY_REASON_PERMISSION_ID = 106;

// inventory movement
export const CHECK_INVENTORY_EXISTENCE_PERMISSION_ID = 117;
export const CHECK_INVENTORY_MOVEMENT_PERMISSION_ID = 118;



export const CHECK_INVENTORY_COUNT_PERMISSION_ID = 150;
export const UPDATE_INVENTORY_COUNT_PERMISSION_ID = 151;
export const ACTION_INVENTORY_COUNT_PERMISSION_ID = 152;
export const BLOCK_INVENTORY_COUNT_DETAIL__PERMISSION_ID = 153;
export const FINALIZED_INVENTORY_COUNT_DETAIL__PERMISSION_ID = 154;
export const CANCELED_INVENTORY_COUNT_DETAIL__PERMISSION_ID = 155;

// inventory adjustment
export const CHECK_INVENTORY_ADJUSTMENT_PERMISSION_ID = 146;
export const UPDATE_INVENTORY_ADJUSTMENT_PERMISSION_ID = 147;
export const CANCEL_INVENTORY_ADJUSTMENT_PERMISSION_ID = 148;
export const FINISH_INVENTORY_ADJUSTMENT_PERMISSION_ID = 149;

// inventory product history report
export const CHECK_PRODUCT_HISTORY_REPORT_ID = 258;
export const CHECK_PRODUCT_HISTORY_REPORT_COST_FIELDS_ID = 259;

// inventory count report
export const CHECK_INVENTORY_COUNT_REPORT_ID = 261;

// inventory adjustment report
export const CHECK_INVENTORY_ADJUSTMENT_REPORT_ID = 262;
export const CHECK_INVENTORY_ADJUSTMENT_REPORT_COSTS_FIELDS_ID = 263;
export const CHECK_INVENTORY_ADJUSTMENT_REPORT_PRICES_FIELDS_ID = 264;

// inventory existence product detail
export const CHECK_INVENTORY_EXISTENCE_PRODUCT_DETAILS_ID = 257;

// inventory OFFICE COMPARATIVES report
export const CHECK_OFFICE_COMPARATIVES_REPORT_ID = 475;
export const CHECK_OFFICE_COMPARATIVES_REPORT_COST_FIELDS_ID = 476;

//#endregion




//#region "Mpc Producto"

// export const CHECK_PRODUCT_PUBLICATION=0;
// export const UPDATE_PRODUCT_PUBLICATION=0;

//#endregion "Mpc Producto

//#region "MRP"

export const CHECK_PLAN_RECIPE_PERMISSION_ID = 111;

// Processing Room
export const UPDATE_PROCESSINGROOM_PERMISSION_ID = 132;
export const CHECK_PROCESSINGROOM_PERMISSION_ID = 133;

// Processing Room Recipe
export const UPDATE_PROCESSINGROOMRECIPE_PERMISSION_ID = 134;
export const CHECK_PROCESSINGROOMRECIPE_PERMISSION_ID = 135;

// Processing Recipe
export const CHECK_RECIPE_PERMISSION_ID = 138;
export const UPDATE_RECIPE_PERMISSION_ID = 139;

// Processing Recipe Ingredients
export const CHECK_RECIPE_INGREDIENTS_PERMISSION_ID = 140;
export const UPDATE_RECIPE_INGREDIENTS_PERMISSION_ID = 141;

// Processing Ingredients
export const CHECK_INGREDIENTS_PERMISSION_ID = 142;
export const UPDATE_INGREDIENTS_PERMISSION_ID = 143;

// Substitute Ingredients

export const CHECK_SUBSTITUTE_INGREDIENT_PERMISSION_ID = 144;
export const UPDATE_SUBSTITUTE_INGREDIENT_PERMISSION_ID = 145;

// Raw Materials and Materials

export const CHECK_RAWMATERIALS_PERMISSION_ID = 136;
export const SHOW_RAWMATERIALS_DETAIL_PERMISSION_ID = 137;

// Production Plans

export const CHECK_PRODUCTION_PLANS_PERMISSION_ID = 244;
export const UPDATE_PRODUCTION_PLANS_PERMISSION_ID = 245;

//#endregion

// Production Orders

export const CHECK_PRODUCTION_ORDER_PERMISSION_ID = 246;
export const UPDATE_PRODUCTION_ORDER_PERMISSION_ID = 247;
export const CANCEL_PRODUCTION_ORDER_PERMISSION_ID = 248;

//#endregion

// Cutting Requirements

export const UPDATE_CUTTING_ORDER_PERMISSION_ID = 237;
//#endregion

//#region SRM

//// INSERT TYPE MODULES

export const CHECK_CATALOGUE_SRM_PERMISSION_ID = 220; // no tomo en cuenta
export const UPDATE_PRODUCT_SUPPLIER_PERMISSION_ID = 221;
export const UPDATE_PRODUCT_SUPPLIER_LOT_PERMISSION_ID = 222;
export const INACTIVE_PRODUCT_SUPPLIER_PERMISSION_ID = 222;
export const CHECK_RECEPTION_PERMISSION_ID = 345;

//#endregion

//#region FINANCIERO
export const WRITE_AUXILIARY_PERMISSION_ID = 142;
export const READ_AUXILIARY_PERMISSION_ID = 141;

export const WRITE_LEDGER_ACCOUNT_CATEGORY_PERMISSION_ID = 140;
// export const READ_LEDGER_ACCOUNT_CATEGORY_PERMISSION_ID = 139;

export const WRITE_COST_CENTER_PERMISSION_ID = 138;

export const WRITE_LOT_PERMISSION_ID = 160;
export const READ_LOT_PERMISSION_ID = 159;
// export const READ__COST_CENTER_PERMISSION_ID = 137;

//#endregion
////#region purchase order
export const UPDATE_PURCHASE_ORDER_PERMISSION_ID = 341;
export const CHECK_PURCHASE_ORDER_PERMISSION_ID = 342;
export const ELABORATED_PURCHASE_ORDER_PERMISSION_ID = 348;
export const AUTHORIZED_PURCHASE_ORDER_PERMISSION_ID = 349;
export const CANCELED_PURCHASE_ORDER_PERMISSION_ID = 350;
export const SEND_REVISION_PURCHASE_ORDER_PERMISSION_ID = 351;
export const CHECK_DISTRIBUTION__PURCHASE_ORDER_PERMISSION_ID = 389;
export const MANAGE_DISTRIBUTION__PURCHASE_ORDER_PERMISSION_ID = 390;

export const UPDATE_ODC_PROVIDER=460;
export const PROVIDER_START_REVIEW=461;
export const PROVIDER_REJECT_REVIEW=462;
export const PROVIDER_FINISH_REVIEW=463;

//#endregion

//#region "TMS"

export const CHECK_REQUEST_SETUP_PERMISSION_ID = 332;
export const UPDATE_REQUEST_SETUP_PERMISSION_ID = 333;

export const CHECK_DRIVER_PERMISSION_ID = 334;
export const UPDATE_DRIVER_PERMISSION_ID = 335;

export const CHECK_VEHICLE_PERMISSION_ID = 336;
export const UPDATE_VEHICLE_PERMISSION_ID = 337;

export const CHECK_ROUTE_PERMISSION_ID = 338;
export const UPDATE_ROUTE_PERMISSION_ID = 339;

export const UPDATE_TRANSFER_PERMISSION_ID = 404;
export const SEND_TRANSFER_PERMISSION_ID = 405;
export const RECEIVE_TRANSFER_PERMISSION_ID = 406;
export const FINALIZE_TRANSFER_PERMISSION_ID = 489;
export const CANCEL_TRANSFER_ERASER_PERMISSION_ID = 490;
export const CANCEL_TRANSFER_SENT_PERMISSION_ID = 491;
export const CANCEL_TRANSFER_RECEIVE_PERMISSION_ID = 492;
export const CANCEL_TRANSFER_FINALIZE_PERMISSION_ID = 493;

//#endregion

//#region Reception

export const CHECK_RECEPTION_VDR_PERMISSION_ID = 353;
export const CREATE_ODC_RECEPTION_VDR_PERMISSION_ID = 354;
export const CREATE_RECEPTION_VDR_PERMISSION_ID = 355;
export const EDIT_RECEPTION_VDR_PERMISSION_ID = 356;
export const FINALIZE_RECEPTION_VDR_PERMISSION_ID = 357;
export const START_RECEPTION_VDR_PERMISSION_ID = 358;
export const VOID_RECEPTION_VDR_PERMISSION_ID = 359;
export const FINALIZE_VALIDATION_RECEPTION_VDR_PERMISSION_ID = 360;
export const START_VALIDATION_RECEPTION_VDR_PERMISSION_ID = 361;
export const PLANNING_RECEPTION_VDR_PERMISSION_ID = 362;
export const REJECT_RECEPTION_VDR_PERMISSION_ID = 458;
export const VIEW_VALIDATION_PERMISSION_ID = 544;
export const CONFIGURE_PRICES_VALIDATIONS_PERMISSION_ID = 545;
export const CONFIGURE_TAXABLE_PRODUCT_PERMISSION_ID = 546;
export const CONFIGURE_DEDUCTIBKLE_PRODUCT_PERMISSION_ID = 547;
export const CONFIGURE_TAXABLE_MASIVE_PERMISSION_ID = 548;
export const CONFIGURE_DEDUCTIBLE_MASIVE_PERMISSION_ID = 549;
export const CONFIGURE_TAXABLE_HEADER_PERMISSION_ID = 550;
export const CONFIGURE_DEDUCTIBLE_HEADER_PERMISSION_ID = 551;

//#endregion

//#region factura consignacion
export const CHECK_CONSIGNMENT_INVOICE_PERMISSION_ID = 552;
export const CREATE_CONSIGNMENT_INVOICE_PERMISSION_ID = 553;

//#endregion

//Weight Instrument
export const UPDATE_WEIGHT_INSTRUMENT_ID = 365;
export const CHECK_WEIGHT_INSTRUMENT_ID = 366


//Child receptions

export const UPDATE_CHILD_RECEPTIONS_ID = 467;


//Purchase order review
export const START_PURCHASE_ORDER_REVIEW_ID = 461;
export const REJECT_PURCHASE_ORDER_REVIEW_ID = 462;
export const FINISH_PURCHASE_ORDER_REVIEW_ID = 463;


// Valued inventory report
export const CHECK_VALUED_INVENTORY_REPORT_ID = 477;

export const CHECK_PRODUCT_ROTATION_REPORT_ID = 478;
// inventory product abc report
export const CHECK_PRODUCT_ABC_REPORT_ID = 473;
export const CHECK_PRODUCT_ABC_REPORT_COST_FIELDS_ID = 474;

//#region "HCM"     

export const MANAGE_INDICATORS_HCM_PERMISSION_ID = 391;
export const CHECK_COMPANY_HCM_PERMISSION_ID = 164;
export const CHECK_EMPLOYEE_HCM_PERMISSION_ID = 165;
export const CHECK_CONCEPT_HCM_PERMISSION_ID = 166;
export const CHECK_VAR_HCM_PERMISSION_ID = 167;
export const CHECK_PAYROLL_CALENDAR_HCM_PERMISSION_ID = 168;
export const CHECK_SALARY_HCM_PERMISSION_ID = 169;
export const CHECK_HOLIDAY_HCM_PERMISSION_ID = 170;
export const CHECK_PAYROLL_DATA_PERMISSION_ID = 532;
export const CHECK_SALARY_BANDS_PERMISSION_ID = 534;
export const CHECK_INDIVIDUAL_ADJUSTMENT_PERMISSION_ID = 536;
export const CHECK_JOB_POSITION_ADJUSTMENT_HCM_PERMISSION_ID = 538;
export const CHECK_MASSIVE_ADJUSTMENT_PERMISSION_ID = 542;
export const CHECK_LOAN_PERMISSION_ID = 171;
export const CHECK_IMPORT_ADJUSTMENT_PERMISSION_ID = 540;
export const MANAGE_COMPANY_HCM_PERMISSION_ID = 190;
export const MANAGE_EMPLOYEE_HCM_PERMISSION_ID = 191;
export const MANAGE_CONCEPT_HCM_PERMISSION_ID = 192;
export const MANAGE_VAR_HCM_PERMISSION_ID = 193;
export const MANAGE_PAYROLL_CALENDAR_HCM_PERMISSION_ID = 194;
export const MANAGE_SALARY_HCM_PERMISSION_ID = 195;
export const MANAGE_HOLIDAY_HCM_PERMISSION_ID = 196;
export const MANAGE_PAYROLL_DATA_PERMISSION_ID = 533;
export const MANAGE_SALARY_BANDS_PERMISSION_ID = 535;
export const MANAGE_INDIVIDUAL_ADJUSTMENT_PERMISSION_ID = 537;
export const MANAGE_JOB_POSITION_ADJUSTMENT_HCM_PERMISSION_ID = 539;
export const MANAGE_MASSIVE_ADJUSTMENT_PERMISSION_ID = 543;
export const MANAGE_IMPORT_ADJUSTMENT_PERMISSION_ID = 541;
export const MANAGE_LOAN_PERMISSION_ID = 197;

// export const CHECK_PERSONAL_DATA_PERMISSION_ID = ;
// export const MANAGE_PERSONAL_DATA_PERMISSION_ID = ;

//#endregion
