export class SalesReportDetail {
  idPackaging: number = -1
  presentation: string = ""
  typePacket: string = ""
  unitperpackagin: number = 0
  gtin: string = ""
  supplier: string = ""
  quantitySold: number = 0
  totalPVP: number = 0
  totalPVPConvertion: number = 0
  cost: number = 0
  costbase: number = 0
  costConvertion: number = 0
  pvp: number = 0
  pvpConvertion: number = 0
  msv: number = 0
  existences: number = 0
  existencesUnds: number = 0
}