import { PurchaseOrderdeductibleDetail } from "./purchase-order-detail-deductible";
import { PurchaseOrderProductPrice } from "./purchase-order-product-price";
import { PurchaseOrdertaxableDetail } from "./purchase-order-taxable-detail";
import { PurchaseOrderTotalProduct } from "./purchase-order-total-product";

export class PurchaseOrderProduct {

    id:number=-1;
    idOrderPurchase:number=-1;
    productId:number=-1;
    image: string = "";
    name:string="";
    internalReference:string="";
    gtin:string="";
    internalReferencesearch:string="";
    gtinsearch:string="";
    idPackaging:number=-1;
    packaging:string="";
    unitPerPackaging:number=0;
    indHeavy:boolean=false;
    packagingQuantity:number=0;
    idPackagingType:number=-1;
    packagingType:string="";
    totalUnits:number=0;
    negotiationCost:number=0;
    createdbyId:number=-1;
    createdby:string="";
    updatedbyId:number=-1;
    updatedby:string="";
    createdDate:Date;
    updatedDate:Date;
    totalCost:number=0;
    supplierReference:string="";
    category:string="";
    brand:string="";
    baseCost:number=0;
    baseCostUnit:number=0;
    baseCostTotal:number=0;
    convertionCostUnit:number=0;
    convertionCostTotal:number=0;
    sellingFactor:number=0;
    minFactor:number=0;
    mediumFactor:number=0;
    maxFactor:number=0;
    netCost :number=0;
    netCostConversion :number=-0;
    salesNetCost :number=0;
    salesNetCostConvertion :number=0;
    pvpBase :number=0;
    pvpConversion :number=0;
    discount:number=0;
    unitmedition:string="";
    indconsigment :number=-1;
    status:number=-1;
    indAdd :number=1;
    baseCalculus:boolean=false;
    internExchangeRate:number=0;
    supplierExchangeRate:number=0;
    prices : PurchaseOrderProductPrice[];
    individualPrices : PurchaseOrderProductPrice = new PurchaseOrderProductPrice();
    masterPrices : PurchaseOrderProductPrice = new PurchaseOrderProductPrice();
    totalproduct:PurchaseOrderTotalProduct = new PurchaseOrderTotalProduct();
    taxables:PurchaseOrdertaxableDetail[];
    deductibles:PurchaseOrderdeductibleDetail[];
    ///resumenes///
    itemscompletes:number=0;
    itemsCost:number=0;
    itemsPVP:number=0;
    totalCostbase:number=0;
    totalcostconvertion:number=0;
    totalnetcost:number=0;
    totalnetcostConvertion:number=0;
    totaltaxables:number=0;
    totalDeductible:number=0;
    subtotal:number=0;
    subtotalConvertion:number=0;
    puchaseTotalTaxable:number=0;
    puchaseTotalDeductible:number=0; 
    indApply:number=0;   
}